AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RequisitionConsumerFn

  Sample SAM Template for RequisitionConsumerFn
Parameters:
  PowerToolsLayerArn:
    Type: 'String'
  DynamoDbPolicyResource:
    Type: 'String'
  DynamoDbRequisitionQueryPolicyResource:
    Type: 'String'
  Environment:
    Type: 'String'

Resources:
  RequisitionConsumerFn:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: RequisitionConsumerFn
      CodeUri: functions/requisition_consumer/
      Handler: requisition_consumer.lambda_handler
      Runtime: python3.10
      Timeout: 120
      Architectures:
      - x86_64
      Layers:
      - arn:aws:lambda:us-west-2:916246436722:layer:aws_lambda_powertools-layer:2    
      Environment:
        Variables:
          environment: dev
          np_attrition_expiration_timestamp_offset: 123456677
      Policies:
      - Version: '2012-10-17'
        Statement: 
        - Sid: QueryDynamoPolicy
          Effect: Allow
          Action: 
          - dynamodb:Query
          - dynamodb:Scan
          Resource:
          - !Ref DynamoDbPolicyResource
          - !Ref DynamoDbRequisitionQueryPolicyResource
        - Sid: UpdateDynamoPolicy
          Effect: Allow
          Action: dynamodb:UpdateItem
          Resource: !Ref DynamoDbPolicyResource
