# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "RequisitionConsumerFn"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "RequisitionConsumerFn"
region = "us-west-2"
image_repositories = []
profile = "dev-team1-prod"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
stack_name = "RequisitionConsumerFn"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "RequisitionConsumerFn"
region = "us-west-2"
image_repositories = []
profile = "dev-team1"
parameter_overrides = [
    "Environment=dev",
    "PowerToolsLayerArn=arn:aws:lambda:us-west-2:916246436722:layer:aws_lambda_powertools-layer:2",
    "DynamoDbPolicyResource=arn:aws:dynamodb:us-west-2:916246436722:table/BHC_REQUISITIONS",
    "DynamoDbRequisitionQueryPolicyResource=arn:aws:dynamodb:us-west-2:916246436722:table/BHC_REQUISITIONS/index/requisition_status-index",
    "ExpirationTimeStampOffset=2592000"
] 

[prod.deploy.parameters]
stack_name = "central-ops-auth-processor-sfn"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "central-ops-auth-processor-sfn"
region = "us-west-2"
image_repositories = []
profile = "dev-team1-prod"
parameter_overrides = [
    "Environment=prod",
    "PowerToolsLayerArn=arn:aws:lambda:us-west-2:043270149596:layer:aws_lambda_powertools-layer:1",
    "DynamoDbPolicyResource=arn:aws:dynamodb:us-west-2:043270149596:table/BHC_REQUISITIONS",
    "DynamoDbRequisitionQueryPolicyResource=arn:aws:dynamodb:us-west-2:043270149596:table/BHC_REQUISITIONS/index/requisition_status-index",
] 